[package]
name = "aoc"
version = "0.1.0"
authors = ["Tai An Su <i@taian.su>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = 'aoc2019'
path = "src/day3.rs"

[dependencies]
itertools = "~0.8.2"
